apiVersion: gateway.solo.io/v1
kind: VirtualService
metadata:
  name: my-aks-vs
  namespace: gloo-system
spec:
  virtualHost:
    domains:
    - '*'
    routes:
    - matchers:
      - prefix: /linux
      routeAction:
        single:
          upstream:
            name: default-azure-vote-front-80
            namespace: gloo-system
      options:
        prefixRewrite: '/'
    - matchers:
      - prefix: /windows
      routeAction:
        single:
          upstream:
            name: default-sample-80
            namespace: gloo-system
      options:
        prefixRewrite: '/'
